Return-Path: <moodle@bar.invalid>
Date: Fri, 13 Apr 2012 12:00:02 +0200
Return-Path: moodle@bar.invalid
To: "Michael Stapelberg" <foo@bar.invalid>
From: "=?utf-8?B?THV0eiBTdHLDvG5nbWFubg==?=" <l.struengmann@bar.invalid>
Subject: =?utf-8?B?QUZTMjAxMjogQXVmZ2FiZW46IFB1bmt0ZSDDnGJ1bmcgMQ==?=
Message-ID: <0ba81486243611670b534d4564ee3718@localhost.localdomain>
X-Priority: 3
X-Mailer: PHPMailer [version Moodle 2007101590]
MIME-Version: 1.0
Content-Type: multipart/alternative;
	boundary="b1_0ba81486243611670b534d4564ee3718"
X-DSPAM-Result: Innocent
X-DSPAM-Processed: Fri Apr 13 12:08:16 2012
X-DSPAM-Confidence: 0.9899
X-DSPAM-Probability: 0.0000
X-DSPAM-Signature: 4f87fb10319744089468961


--b1_0ba81486243611670b534d4564ee3718
Content-Type: text/plain; charset = "UTF-8"
Content-Transfer-Encoding: quoted-printable


AFS2012 -> Aufgaben -> Punkte =C3=9Cbung 1
---------------------------------------------------------------------
Lutz Str=C3=BCngmann hat einen Kommentar zu Ihrer eingereichten Aufgabe =
'Punkte
=C3=9Cbung 1' verfasst.

Sie finden ihn im Anhang Ihrer abgegebenen Aufgabe:

http://moodle.hs-mannheim.de/mod/assignment/view.php?id=3D11205
---------------------------------------------------------------------



--b1_0ba81486243611670b534d4564ee3718
Content-Type: text/html; charset = "UTF-8"
Content-Transfer-Encoding: quoted-printable

<p><font face=3D"sans-serif"><a =
href=3D"http://moodle.hs-mannheim.de/course/view.php?id=3D666">AFS2012</a> =
-><a href=3D"http://moodle.hs-mannheim.de/mod/assignment/index.php?id=3D66=
6">Aufgaben</a> -><a href=3D"http://moodle.hs-mannheim.de/mod/assignment/v=
iew.php?id=3D11205">Punkte =C3=9Cbung 1</a></font></p><hr /><font =
face=3D"sans-serif"><p>Lutz Str=C3=BCngmann hat einen Kommentar zu Ihrer =
abgegebenen Aufgabe verfasst.</i>'<i>Punkte =C3=9Cbung 1</i>'<br /><br />
Sie finden ihn im Anhang Ihrer=20
<a href=3D"http://moodle.hs-mannheim.de/mod/assignment/view.php?id=3D11205=
">eingereichten Aufgabe</a>:.</p></font><hr />



--b1_0ba81486243611670b534d4564ee3718--


