Date: Sat, 10 Mar 2012 17:35:17 +0100
From: Jakob Haufe <sur5r@sur5r.net>
To: Allgemeine Diskussionsliste des Chaostreffs Heidelberg <ccchd@ccchd.de>
Message-ID: <20120310173517.0ce1d1a2@samsa.ccchd.dn42>
Mime-Version: 1.0
Subject: [ccchd] Zertifikatstausch auf discordia
Content-Type: multipart/mixed; boundary="===============1597656824=="

This is a MIME-formatted message.  If you see this text it means that your
E-mail software does not support MIME-formatted messages.

--===============1597656824==
Content-Type: multipart/signed; micalg=PGP-SHA1; protocol="application/pgp-signature"; boundary="=_libri-16100-1331397356-0001-2"

This is a MIME-formatted message.  If you see this text it means that your
E-mail software does not support MIME-formatted messages.

--=_libri-16100-1331397356-0001-2
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

Hi zusammen!

Die SSL-Zertifikate auf discordia laufen morgen ab, daher werde ich sie heu=
te
durch neue ersetzen. Da CAcert die alten Zertifikate automatisch revoked
sobald man die neuen erstellt werde ich die betroffenen Dienste vor=C3=BCbe=
rgehend
anhalten und erst nach Einspielen der neuen Zertifikate wieder starten.

Gr=C3=BC=C3=9Fe,
Jakob

--=20
ceterum censeo microsoftem esse delendam.

--=_libri-16100-1331397356-0001-2
Content-Type: application/pgp-signature
Content-Transfer-Encoding: 7bit
Content-Disposition: inline

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1.4.11 (GNU/Linux)

iEYEARECAAYFAk9bgsUACgkQ1YAhDic+adYNHACdGAEnqQ448icP95hiMl7ro0QH
pjQAn3cd39rUfmqI40qplcnKWIjkeKCD
=oiKO
-----END PGP SIGNATURE-----

--=_libri-16100-1331397356-0001-2--

--===============1597656824==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Disposition: inline

-- 
ccchd mailing list
ccchd@ccchd.de
https://discordia.noname-ev.de/cgi-bin/mailman/listinfo/ccchd

--===============1597656824==--

