Subject: Bug#645898: ITP: jimtcl -- Jim is a small-footprint implementation of Tcl.
Reply-To: Didier Raboud <odyx@debian.org>, 645898@bugs.debian.org
Resent-From: Didier Raboud <odyx@debian.org>
Resent-To: debian-bugs-dist@lists.debian.org
Resent-CC: debian-devel@lists.debian.org, wnpp@debian.org
X-Loop: owner@bugs.debian.org
Resent-Date: Wed, 19 Oct 2011 13:21:26 +0000
Resent-Message-ID: <handler.645898.B.131903037910023@bugs.debian.org>
Received: via spool by submit@bugs.debian.org id=B.131903037910023
          (code B ref -1); Wed, 19 Oct 2011 13:21:26 +0000
Received: (at submit) by bugs.debian.org; 19 Oct 2011 13:19:39 +0000
MIME-Version: 1.0
Content-Type: text/plain; charset="UTF-8"
From: Didier Raboud <odyx@debian.org>
To: Debian Bug Tracking System <submit@bugs.debian.org>
Message-ID: <20111019125600.25860.44016.reportbug@Tamino>
X-Mailer: reportbug 6.2.2
Date: Wed, 19 Oct 2011 14:56:00 +0200
X-MIME-Autoconverted: from 8bit to quoted-printable by smtp2.infomaniak.ch id p9JCu0ji020915
Delivered-To: submit@bugs.debian.org
X-Rc-Virus: 2007-09-13_01
X-Mailing-List: <debian-devel@lists.debian.org> archive/latest/276354
X-Loop: debian-devel@lists.debian.org
Resent-Sender: debian-devel-request@lists.debian.org
Content-Transfer-Encoding: 8bit
X-MIME-Autoconverted: from quoted-printable to 8bit by mx02.rent-a-guru.de id p9JDLx1F243014019

Package: wnpp
Severity: wishlist
Owner: Didier Raboud <odyx@debian.org>

-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

  Package name    : jimtcl
  Version         : 0.72
  Upstream Author : Steve Bennnett <steveb@workware.net.au>, Øyvin Harboe <oyvind.harboe@zylin.com>
  URL             : http://jim.berlios.de/
  License         : FreeBSD
  Programming Lang: C
  Description     : Jim is a small-footprint implementation of Tcl.

Jim is a small-footprint implementation of the Tcl programming language. It
implements a large subset of Tcl and adds new features like references with
garbage collection, closures, built-in Object Oriented Programming system,
Functional Programming commands, first-class arrays and UTF-8 support. All
this with a binary size of about 100-200kB (depending upon selected options).

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1.4.11 (GNU/Linux)

iQGcBAEBCAAGBQJOnsjeAAoJEIvPpx7KFjRVpTQL/jMjc3p2uvgrgS9/pGTPEfoS
dv86Yrlygzetjwt5z5gqejsG2ZnQAnPryfahi4ca7sYSe4CHkkQJOopkcrcJUisX
7H/cdbSrWm6yoVyW8hgYPohgEw2DuYCxIocmBALScXUCFEuOcKOzL7IA9eO6xhpO
21fR75Pqqb1ozCcw4MUSahthAd0TEXnDyikyUmDJuizJgqn2z8p8vp+NCLe7Orho
/PuKs05LsQhlyMMBAGoy+XnSrSa4DOMBdZUvqOKxPvf082Md73AfmLz7ZMqZGmaB
2OJRZLGw3LGjIAIlCCVkkwEm5c5XOwjU0GkyOB397pdlkVgL6zQ3lqH8ajMGcKN8
QX95+CObetn19HU7cSGh2KfyzpNdLufcoEeFr6J0b71V2cdVvrSFQMkiqhd3fUD9
/VyLlXkw9/dp341e06f6ICqntHFWmUpolHcANFXlCqZzBtnWD0bpP72EdW9rMXtl
1bYvafww2xnjL4Gg18HFEyXZbjGxgT7ZOy9CxF2Gig==
=xG9K
-----END PGP SIGNATURE-----



-- 
To UNSUBSCRIBE, email to debian-devel-REQUEST@lists.debian.org
with a subject of "unsubscribe". Trouble? Contact listmaster@lists.debian.org
Archive: http://lists.debian.org/20111019125600.25860.44016.reportbug@Tamino

