#
# Autogenerated by Thrift
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift/protocol'

module Heliotrope
    class Document
      include Thrift::Struct
      Thrift::Struct.field_accessor self, :id, :metadata, :body, :body_size
      FIELDS = {
        1 => {:type => Thrift::Types::I32, :name => 'id'},
        2 => {:type => Thrift::Types::MAP, :name => 'metadata', :key => {:type => Thrift::Types::STRING}, :value => {:type => Thrift::Types::STRING}},
        3 => {:type => Thrift::Types::STRING, :name => 'body'},
        4 => {:type => Thrift::Types::I32, :name => 'body_size'}
      }
    end

    class Tree
      include Thrift::Struct
      Thrift::Struct.field_accessor self, :id, :type, :metadata, :doc_ids, :doc_depths
      FIELDS = {
        1 => {:type => Thrift::Types::I32, :name => 'id'},
        2 => {:type => Thrift::Types::STRING, :name => 'type'},
        3 => {:type => Thrift::Types::MAP, :name => 'metadata', :key => {:type => Thrift::Types::STRING}, :value => {:type => Thrift::Types::STRING}},
        4 => {:type => Thrift::Types::LIST, :name => 'doc_ids', :element => {:type => Thrift::Types::I32}},
        5 => {:type => Thrift::Types::LIST, :name => 'doc_depths', :element => {:type => Thrift::Types::I32}}
      }
    end

    class SearchResult
      include Thrift::Struct
      Thrift::Struct.field_accessor self, :tree_id, :doc_id, :search_position
      FIELDS = {
        1 => {:type => Thrift::Types::I32, :name => 'tree_id'},
        2 => {:type => Thrift::Types::I32, :name => 'doc_id'},
        3 => {:type => Thrift::Types::I32, :name => 'search_position'}
      }
    end

    class AddResult
      include Thrift::Struct
      Thrift::Struct.field_accessor self, :tree_id, :doc_id
      FIELDS = {
        1 => {:type => Thrift::Types::I32, :name => 'tree_id'},
        2 => {:type => Thrift::Types::I32, :name => 'doc_id'}
      }
    end

    class GeneralError < StandardError
      include Thrift::Struct
      def initialize(message=nil)
        super()
        self.message = message
      end

      Thrift::Struct.field_accessor self, :message
      FIELDS = {
        1 => {:type => Thrift::Types::STRING, :name => 'message'}
      }
    end

    class NoSuchIdError < StandardError
      include Thrift::Struct
      def initialize(message=nil)
        super()
        self.message = message
      end

      Thrift::Struct.field_accessor self, :message
      FIELDS = {
        1 => {:type => Thrift::Types::STRING, :name => 'message'}
      }
    end

    class NotAChildError < StandardError
      include Thrift::Struct
      def initialize(message=nil)
        super()
        self.message = message
      end

      Thrift::Struct.field_accessor self, :message
      FIELDS = {
        1 => {:type => Thrift::Types::STRING, :name => 'message'}
      }
    end

  end
